# RDB 설정 (10초 내 1번 변경 시 저장)
# save "" << 비활성화
# save 10 1 << 10초에 1개 변경 있을때 마다 저정
save ""

# AOF 설정
# AOF 활성화 여부 (yes/no)
appendonly yes
# 디스크 저장 주기
appendfsync everysec

# 기본 포트
port 6379

# 최대 메모리 사용 메모리 설정
maxmemory 0
# 메모리가 가득 찼을 경우 설정
maxmemory-policy allkeys-lru